apiVersion: v1
kind: Service
metadata:
  name: lemon-backend-api
  namespace: lemontech
  labels:
    app: lemon-backend
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5000
  selector:
    app: lemon-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemon-backend
  namespace: lemontech
  label:
   app: lemon-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: lemon-backend
  template:
    metadata:
      labels:
        app: lemon-backend
    spec:
      containers:
        - name: lemon-backend
          image: CONTAINER_IMAGE
          securityContext:
            runAsUser: 2000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 5000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lemon-backend-hpa
  namespace: lemontech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lemon-backend
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10            