apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemon-backend
  namespace: lemontech
  labels:
   app: lemon-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lemon-backend
  template:
    metadata:
      labels:
        app: lemon-backend
    spec:
      containers:
        - name: lemon-backend
          image: synopscl/test-lem-back:14
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m  
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lemon-backend-hpa
  namespace: lemontech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lemon-backend
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10            