apiVersion: v1
kind: Service
metadata:
  name: lemon-backend-api
  namespace: lemontech
  labels:
    app: lemon-backend
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5000
  selector:
    app: lemon-backend
---
apiVersion: v1
kind: Service
metadata:
  name: lemon-backend-srv
  namespace: lemontech
  labels:
    app: lemon-backend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: lemon-backend
    