---
kind: pipeline
type: docker
name: backend

steps:
- name: install
  image: ruby:2.6.3
  
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - cd backend
  - gem install bundler:1.17.3
  - bundle install
  - mv .env.sample .env
  - gem install foreman
  - rake db:migrate && foreman start
  
volumes:
- name: bundle
  temp: {}